version: '3.5'
services:
  postgres:
    container_name: audallydb
    image: postgres:11.6
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
       - postgres:/data/postgresBrain
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  postgres:
