version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./docker_pg_init.sql:/docker-entrypoint-initdb.d/docker_pg_init.sql
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5432:5432"
  keycloak:
      image: quay.io/keycloak/keycloak:11.0.0
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: postgres
        DB_USER: postgres
        DB_SCHEMA: keycloak
        DB_PASSWORD: postgres
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
      ports:
        - 8180:8080
      command: -Dkeycloak.profile.feature.upload_scripts=enabled
      depends_on:
        - postgres

